# Generated by Django 4.2.17 on 2025-01-07 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='demo',
        ),
    ]
